[tool.poetry]
name = "lido-oracle"
version = "3.0.0"
description = "Oracle daemon for Lido decentralized staking service. Collects and reports Ethereum 2.0 beacon chain states (the number of visible validators and their summarized balances) to the Lido dApp contract running on Ethereum 1.0 side."
authors = ["Raman Siamionau", "Kirill Varlamov", "Smelov Vladimir", "Dmitry Suldin"]
license = "GPL 3.0"

[tool.poetry.dependencies]
python = "^3.11"
web3 = "6.0.0b9"
prometheus-client = "^0.16.0"
web3-multi-provider = "^0.5.0"
timeout-decorator = "^0.5.0"
poetry = "^1.3.2"
frozendict = "^2.3.4"

[tool.poetry.dev-dependencies]
pytest = "^7.2.1"
base58 = "^2.1.1"
ipfshttpclient = "^0.7.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
markers = ["unit: tests that do not require external resources"]