name: Tests and Checks

on: push

jobs:
  security:
    uses: catalistfinance/linters/.github/workflows/security.yml@master
    permissions:
      security-events: write
      contents: read
  docker:
    uses: catalistfinance/linters/.github/workflows/docker.yml@master
  actions:
    uses: catalistfinance/linters/.github/workflows/actions.yml@master
