name: CI Staging

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths-ignore:
      - ".github/**"
      - "README.md"

permissions: {}

jobs:
  # test:
  #   ...

  deploy:
    runs-on: ubuntu-latest
    # needs: test
    name: Build and deploy
    steps:
      - name: Staging deploy
        uses: catalistfinance/dispatch-workflow@v1
        env:
          APP_ID: ${{ secrets.APP_ID }}
          APP_PRIVATE_KEY: ${{ secrets.APP_PRIVATE_KEY }}
          TARGET_REPO: "catalistfinance/infra-mainnet"
          TARGET_WORKFLOW: "deploy_staging_mainnet_catalist_oracle.yaml"
          TARGET: "master"
