name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Setup poetry
      run: |
        curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python - && source $HOME/.poetry/env

    - name: Install dependencies
      run: |
        poetry install

    - name: Lint
      run: ./check_code.sh
      continue-on-error: true

    - name: Test with pytest and Lighthouse beacon
      run: poetry run ./run_tests.sh Lighthouse

    - name: Test with pytest and Prysm beacon
      run: poetry run ./run_tests.sh Prysm

  security:
    uses: lidofinance/linters/.github/workflows/security.yml@master

  docker:
    uses: lidofinance/linters/.github/workflows/docker.yml@master
