name: Tests

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - uses: Gr1N/setup-poetry@v7

    - name: Install dependencies
      run: |
        poetry install

    - name: Lint
      run: ./check_code.sh
      continue-on-error: true

    - name: Test with pytest and Lighthouse beacon
      run: ./run_tests.sh Lighthouse

    - name: Test with pytest and Prysm beacon
      run: ./run_tests.sh Prysm

  security:
    uses: lidofinance/linters/.github/workflows/security.yml@master

  docker:
    uses: lidofinance/linters/.github/workflows/docker.yml@master
